Add keyboard input to plane
rob3rtu/Unity-Project pull request #17
Opened 2023-10-29 17:45 UTC by Qmpzlawasd

2023-10-29 18:12 UTC, widdrr requested changes

2023-10-29 18:12 UTC, widdrr commented on Flight Game/Assets/Scripts/KeyboardInput/PlaneInput.cs
> +
We could add [SerializedField] to _flightPhysics so it's clear the component has this dependency.. That being said it's fine as it is.

2023-10-29 18:12 UTC, widdrr commented on Flight Game/Assets/Scripts/KeyboardInput/PlaneInput.cs
> +}
Please use Unity's Input manager and define the controls there. It will allow greater flexibility

2023-10-29 18:12 UTC, widdrr commented on Flight Game/Assets/Scripts/Plane Physics/FlightPhysics.cs
> +using UnityEditor.IMGUI.Controls;
Is this required?

2023-10-29 18:12 UTC, widdrr commented on Flight Game/Assets/Scripts/Plane Physics/FlightPhysics.cs
> +    }
Perhaps adding some comments explaining in which direction the object will roll depending on magnitude will be helpful. For instance, for ApplyYaw we could mention positive = right, negative = left

2023-10-29 18:12 UTC, widdrr commented on Flight Game/Assets/Scripts/Plane Physics/FlightPhysics.cs
> +    }
I'd restrict some more the usage of the flap. Allowing the caller free range is not ideal. Perhaps the whole flap should be reworked.

2023-10-30 17:52 UTC, widdrr requested changes

2023-10-30 17:52 UTC, widdrr commented on Flight Game/Assets/Scripts/KeyboardInput/PlaneInput.cs
> +        }
Why do we enclose the call in if statements for most of these?
Should't `_flightPhysics.ApplyPitchTorque(Input.GetAxis("Vertical"));` suffice?

2023-10-30 17:59 UTC, Qmpzlawasd commented on Flight Game/Assets/Scripts/KeyboardInput/PlaneInput.cs
> +        }
> Why do we enclose the call in if statements for most of these? Should't `_flightPhysics.ApplyPitchTorque(Input.GetAxis("Vertical"));` suffice?

Theoretically, yes, but relentlessly calling these functions could induce some overhead.

2023-10-30 18:22 UTC, widdrr commented on Flight Game/Assets/Scripts/KeyboardInput/PlaneInput.cs
> +        }
fair point 👍

2023-10-30 18:22 UTC, widdrr approved these changes

2023-10-31 20:30 UTC, merged