Add cube Event
rob3rtu/Unity-Project pull request #80
Opened 2024-01-04 12:41 UTC by Qmpzlawasd

Every time a portal is taken there are cubes falling from the sky and only after some seconds pass, there is a new checkpoint spawning.
It's meant as a bonus level for the player to gather as many points as possible.

2024-01-05 12:04 UTC, widdrr commented on Flight Game/Assets/Scripts/Checkpoints/CheckpointGenerator.cs
> +        _cubeEvent = _checkpointCount % _cubeEventFrequency == 0;
I personally don't like using `_cubeEventFrequency` like this. It makes it less intuitive in how the variable is used. Personally I expect the variable to read like "Cube event every x *levels*" not "Cube event every x *checkpoints*". Moreover if setting the `_cubeEventFrequency` to something not a multiple of `_portalFrequency`, it will cause cube vents to spawn mid level, when I thought the idea was for an entire level to only be the cube event.

PS: I'm okay with the modulo approach.

2024-01-05 12:06 UTC, widdrr commented
Testing results:
-After a cube event finishes, it spawns a normal checkpoint instead of a portal
-We should also set the temporary dev values a bit higher, so we won't have to change them every time we test (it's annoying for a cube event to spawn every level)
-See comment regarding CubeEventFrequency meaning and usage.

2024-01-05 12:08 UTC, widdrr requested changes

2024-01-05 12:08 UTC, widdrr commented on Flight Game/Assets/Scripts/Checkpoints/Checkpoint.cs
> +    public GameObject _plane;
If it's a public member it should not have _

2024-01-06 10:47 UTC, widdrr approved these changes

2024-01-06 14:01 UTC, AdelaCorbeanu commented on Flight Game/Assets/Scripts/Checkpoints/CheckpointGenerator.cs
> +        _cubeEvent = _checkpointCount % _cubeEventFrequency == 0;
What Andrei said is what I had in mind as well, great that you sorted it out!

2024-01-06 14:48 UTC, AdelaCorbeanu approved these changes
Very cool! 🐈

2024-01-06 15:00 UTC, merged